### ISSUE TITLE
DOCS - Lister les features du BO

### ISSUE THREAD

**Issue by fagathe-dev** [fagathe-dev/tavern-bo#3]
# Lister les features de la BO 

### Features :  
- [x] fagathe-dev/tavern-bo#5
- [x] fagathe-dev/tavern-bo#6
- [x] fagathe-dev/tavern-bo#8
- [x] fagathe-dev/tavern-bo#9
- [x] fagathe-dev/tavern-bo#10
- [x] fagathe-dev/tavern-bo#21
- [x] fagathe-dev/tavern-bo#37
- [x] fagathe-dev/tavern-bo#65

### Front 
- [x] fagathe-dev/tavern-bo#35
- [x] fagathe-dev/tavern-bo#59
- [x] fagathe-dev/tavern-bo#24
- [x] fagathe-dev/tavern-bo#23
- [x] fagathe-dev/tavern-bo#27
- [x] fagathe-dev/tavern-bo#25

### Core : 
- [x] fagathe-dev/tavern-bo#32 
- [x] fagathe-dev/tavern-bo#58

### Init: 
- [x] fagathe-dev/tavern-bo#1
- [x] fagathe-dev/tavern-bo#4
- [x] fagathe-dev/tavern-bo#17
- [x] #74
